# Generated by Django 6.0.2 on 2026-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="source_lang",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="target_lang",
            field=models.CharField(blank=True, default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="translation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="urgency",
            field=models.CharField(default="Medium", max_length=20),
        ),
    ]
