# Generated by Django 6.0.2 on 2026-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
